blank_issues_enabled: false
contact_links:
  - name: Orbit Discussions
    url: https://github.com/orbit-format/orbit/discussions
    about: Ask questions or share ideas that are not bugs or feature requests.
